website/views.py
from flask import Blueprint, render_template, redirect,request, flash, jsonify, url_for
from flask_login import login_required, current_user
from .models import Recipe, Ingredient, Instruction,User
from . import db
import json

views = Blueprint('view', __name__)


@views.route('/')
@login_required
def home():
    # Get all the recipes form data
    recipes = Recipe.query.filter_by(user_id=current_user.id).all()
    
    # Fetch the user's first name from the database
    user = User.query.get(current_user.id)
    first_name = user.first_name
    
    # Count the price for one serving
    for recipe in recipes:
        recipe.price_per_person = recipe.price / recipe.people
    
    return render_template("home.html", user=current_user, recipes=recipes, first_name=first_name)


@views.route('/recipes')
@login_required
def recipeList():
    # get all the recipes form data
    recipes = Recipe.query.filter_by(user_id=current_user.id).all()
    #count the price for one serving
    for recipe in recipes:
        recipe.price_per_person = recipe.price / recipe.people
    return render_template("recipes.html", user=current_user, recipes=recipes)


@views.route("/addrecipe", methods=["GET", "POST"])
@login_required
def add_name():
    if request.method == "POST":
        # get the form data
        title = request.form.get("title")
        price = request.form.get("price")
        people = request.form.get("people")
        time = request.form.get("time")
        
        #check that input data type is valid
        if not people.isdigit(): 
            flash("Please use a valid number", category='error')
        elif "," in price:
            flash("Please use a dot (.) as the decimal separator for the price", category='error')
        elif "," in time:
            flash("Please add time in minutes not in hours", category='error')
        else:

            # add the recipe to the database
            recipe = Recipe(title=title, price=price,people=people, time=time, user_id=current_user.id)
            db.session.add(recipe)
            db.session.commit()

            # redirect to the next page in the recipe creation process
            return redirect(url_for("view.addingredients", recipe_id=recipe.id))

    # render the form page
    return render_template("addrecipe.html", user=current_user)


# Adding the ingredients to the recipe
@views.route("/addingredients/<int:recipe_id>", methods=["GET", "POST"])
# Without logging in a user can not access this view
@login_required
def addingredients(recipe_id):
    recipe = Recipe.query.get(recipe_id)

    if request.method == "POST":
        ingredient_name = request.form.get("name")
        ingredient = Ingredient(name=ingredient_name, recipe_id=recipe_id)
        db.session.add(ingredient)
        db.session.commit()
        flash("Ingredient saved", category='info')

    ingredients = Ingredient.query.filter_by(recipe_id=recipe_id).all()
    return render_template('addingredients.html', user=current_user, recipe=recipe, ingredients=ingredients)

# Adding the instructions to the recipe
@views.route("/addinstructions/<int:recipe_id>", methods=["GET", "POST"])
# Without logging in a user can not access this view
@login_required
def addinstructions(recipe_id):
    recipe = Recipe.query.get(recipe_id)

    if request.method == "POST":
        instruction_name = request.form.get("name")
        instruction = Instruction(name=instruction_name, recipe_id=recipe_id)
        db.session.add(instruction)
        db.session.commit()
        flash("Instruction saved", category='info')

    instructions = Instruction.query.filter_by(recipe_id=recipe_id).all()
    return render_template('addinstructions.html', user=current_user, recipe=recipe, instructions=instructions)


@views.route('/delete-recipe')
def delete_recipe():
    # get the recipe from the database
    recipe_id = request.args.get('recipe_id')
    recipe = Recipe.query.get(recipe_id)
    # delete recipe
    db.session.delete(recipe)
    db.session.commit()
    return redirect('/recipes')

website/templates/addingredients.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content %}
<form method="post" class="form2">
    <h1>Add the ingredients</h1>

    {% for ingredient in ingredients %}
        <li>{{ ingredient.name }}</li>
    {% endfor %}

    <p class="ing">The ingredients must be added one by one</p>
    <p>After all ingredients have been added you can find your recipe on the Recipes-page</p>
    <p>
        <input name="name" class="ing" placeholder="For example:   Pasta"/>
    </p>
    <p>
        <button type="submit" class="btn btn-dark">Add an Ingredient</button>
    </p>
</form>
<button type="button" class="btn btn-light">
    <a href="/recipes" class="buttonrecipe">
        Recipes
    </a>
</button>

{% if ingredients|length > 0 %}
    <a href="{{ url_for('view.addinstructions', recipe_id=recipe.id) }}" class="btn btn-secondary">
        Add Instructions
    </a>
{% endif %}

{% endblock %}

website/templates/addinstructions.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
<form method="post" class="form2">
    <h1>Add the instructions</h1>

    {% for instruction in instructions %}
        <li>{{ instruction.name }}</li>
    {% endfor %}

    <p class="ing">The instructions must be added one by one</p>
    <p>After all instructions have been added you can find your recipe on the Recipes-page</p>
    <p>
        <input name="name" class="ing" placeholder=""/>
    </p>
    <p>
        <button type="submit"  class="btn btn-dark">Add a instruction</button>
    </p>
</form>
<button type="button" class="btn btn-light">
    <a href="/recipes" class="buttonrecipe">
        Recipes
    </a>
</button>

{% endblock %}

website/templates/addrecipe.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
    <h1 class="sign" >Add a new Recipe</h1>
    <p class="text"> The first step is to add the recipes name, instructions,<br> 
      how much the ingredients cost, cooking time and how many people it will feed
      <br><br>
      After saving the information below you can add all the ingredients to the recipe</p>
    <form method="POST" style="width: 40%;" class="form2">
      <label>Name of the recipe</label>
      <textarea placeholder="Tea" name="title" id="title" class="form-control" style="height: 50px;"></textarea>
      <br />
      <label>Approximately how much did the ingredients cost</label>
      <textarea placeholder="2.5"name="price" id="price" class="form-control" style="height: 50px;" type="number"></textarea>
      <br />
      <label>Approximately how many people will this recipe feed</label>
      <textarea placeholder="2" name="people" id="people" class="form-control" style="height: 50px;" type="number"></textarea>
      <br />
      <label>Cooking time (please write in minutes) </label>
      <textarea placeholder="50" name="time" id="time" class="form-control" style="height: 50px;" type="number"></textarea>
      <br />      
      <div>
        <button type="submit" class="btn btn-dark">Add Recipe</button>
      </div>
    </form>
    {% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400" rel="stylesheet">
  <title>{% block title %}Recipe{% endblock %}</title>
</head>
<style>
  * {
    font-family: 'Montserrat', sans-serif;
  }

  nav {
    height: 80px;
    display: flex;
  }

  .navbar-nav {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-left:auto;
    margin-right: auto;
  }

  .nav-item {
    margin-right: 20px;
  }

  .nav-user {
    border-radius: 50%;
    background-color: antiquewhite;
    width: 56px;
    height: 56px;
    line-height: 56px;
    text-align: center;
    font-size: small;
    margin-bottom: 2%;
  }

  .form2 {
    width: 40%;
    margin-left: auto;
    margin-right: auto;
    margin-top: 70px;
    margin-bottom: 90px;
  }

  .ins {
    margin-top: 40px;
    font-weight: bold;
  }

  .ins2 {
    margin-top: 20px;
  }

  .form3 {
    width: 50%;
    margin-left: auto;
    margin-right: auto;
    margin-top: 50px;
  }

  .sign {
    margin-top: 90px;
    text-align: center;
  }

  .sign2 {
    left: 0;
    line-height: 200px;
    margin-top: -100px;
    position: absolute;
    text-align: center;
    top: 50%;
    width: 100%;
  }

  .content, .text {
    margin-bottom: 30px;
    text-align: center;
  }

  .ing {
    width: 90%;
    margin-top: 50px;
  }

  .cook {
    float: right;
  }

  .recipe {
      margin-left: auto;
      margin-right: auto;
      padding:30px;
      background-color: rgb(246, 246, 246);
      border-radius: 5px;
      margin-top:30px;
      width: 65%;

  }

  .buttonrecipe {
    text-decoration: none;
    color: rgb(199, 113, 85);
    font-weight: bold;
  }

  .delete_recipe {
    text-decoration: none;
    color: rgb(195, 0, 0);
    float: right;
    font-size:medium;
  }

  .delete_recipe:hover {
    text-decoration: none;
    color: rgb(95, 0, 0);
  }


  @media (max-width: 1024px) {

    .navbar-nav {
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: rgb(249, 249, 249);
    }
    .nav-user {
      margin-bottom: 3%;
    }

    .recipe, .addrecipe {
      width: 100%;
    }

  }

  .alert.alert-success {
    background-color: #dff0d8; 
    border-color: #d6e9c6; 
    color: #3c763d; 
    text-align: center;
    width: 30%;
    margin-right: auto;
    margin-left: auto;
    margin-top: 2%;

  }

</style>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Recipe Haven</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    {% if user.is_authenticated %}
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" id="home" href="/">Home  <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="recipes" href="/recipes">Recipes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="add" href="/addrecipe">Add Recipe</a>
      </li>
      <li class="nav-item nav-link nav-user">{{ user.first_name }}</li>
      <li class="nav-item">
        <a class="nav-item nav-link nav-log" id="logout" href="/logout">Logout</a>
      </li>
    </ul>
    {% else %}
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-item nav-link" id="login" href="/login">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
      </li>
    </ul>
    {% endif %}
  </div>
</nav>


{% with messages = get_flashed_messages(with_categories=true) %} {% if
messages %} {% for category, message in messages %} {% if category ==
'error' %}
<div class="alert alert-danger alter-dismissable fade show" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% else %}
<div class="alert alert-success alter-dismissable fade show" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %} {% endfor %} {% endif %} {% endwith %}

<div class="container">{% block content %} {% endblock %}</div>
<script
  type="text/javascript"
  src="{{ url_for('static', filename='index.js') }}"
></script>
<script>
  // Function to fade out the flash message element
  function fadeOutFlashMessage(flashId) {
    var flashElement = $("#" + flashId);
    if (flashElement) {
      flashElement.fadeOut(500); // 500ms fade-out effect
    }
  }

  // Fade out flash messages after 5 seconds (5000 milliseconds)
  setTimeout(function() {
    fadeOutFlashMessage("flash-success");
    fadeOutFlashMessage("flash-error");
    fadeOutFlashMessage("flash-info");
  }, 5000);
</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>

website/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="sign">{% block title %} Welcome {{ user.first_name }} {% endblock %}</h1>
    <div class="content">
        <p>Home page here</p>
    </div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<h3 align="center" class="sign">Login</h3>
<form method="POST" class="form3">
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/recipes.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="sign">{% block title %}{{ user.first_name }}'s Recipes {% endblock %}</h1>
    <div class="addrecipe">
        {% if recipes %}
            {% for recipe in recipes %}
                <div class="recipe">
                    <p>
                        <h3>{{ recipe.title }}
                            <a class="delete_recipe" href="{{ url_for('view.delete_recipe', recipe_id=recipe.id) }}">delete</a>
                        </h3>
                    </p>
                    <p class="cook"> Cooking time: {{ recipe.time }} minutes</p>
                    <b>
                        <p class="name">Serves: {{ recipe.people }}</p>
                        <p>Price per person:  {{ "$%.2f"|format(recipe.price_per_person) }}€</p>

                        <p class="ins">Ingredients</p>
                        {% for ingredient in recipe.ingredients %}
                        <li>{{ ingredient.name }}</li>
                        {% endfor %}
                    </b>
                    <p class="ins">Instructions</p>
                    <ol> {# Move the <ol> tag outside the loop #}
                        {% for instruction in recipe.instructions %}
                        <li>{{ instruction.name }}</li>
                        {% endfor %}
                    </ol> {# Close the <ol> tag here #}
                </div>
            {% endfor %}
        {% else %}
            <p class="sign2">No recipes added</p>
        {% endif %}
    </div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <h3 align="center" class="sign">Sign Up</h3>
    <form method="POST" class="form3">
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="form-control"
          id="firstName"
          name="firstName"
          placeholder="Enter first name"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}